"""The model itself: how it encodes, predicts, imagines the future, and scores plans. Exports to `lewm/jepa.py`."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_jepa.ipynb.

# %% auto #0
__all__ = ['detach_clone', 'JEPA']

# %% ../nbs/01_jepa.ipynb #a3aeb9e9
"""JEPA Implementation"""

import torch
import torch.nn.functional as F
from einops import rearrange
from torch import nn

# %% ../nbs/01_jepa.ipynb #b4ab4a61
def detach_clone(v):
    """Detached, independent copy of a tensor; anything else is returned as-is."""
    return v.detach().clone() if torch.is_tensor(v) else v

# %% ../nbs/01_jepa.ipynb #1450a997
class JEPA(nn.Module):
    """Joint Embedding Predictive Architecture.

    Args:
        encoder: image -> tokens. A ViT; only its CLS token is used.
        predictor: ARPredictor. (emb, act_emb) -> next emb.
        action_encoder: Embedder. raw actions -> embeddings.
        projector: optional MLP head after the encoder.
        pred_proj: optional MLP head after the predictor.
    """

    def __init__(
        self,
        encoder,
        predictor,
        action_encoder,
        projector=None,
        pred_proj=None,
    ):
        super().__init__()

        self.encoder = encoder
        self.predictor = predictor
        self.action_encoder = action_encoder
        # Identity keeps the call sites uniform when no head is configured.
        self.projector = projector or nn.Identity()
        self.pred_proj = pred_proj or nn.Identity()

    def encode(self, info):
        """Encode observations and actions into embeddings.
        info: dict with pixels and action keys

        Reads  info["pixels"]  (B, T, C, H, W)
               info["action"]  (B, T, A)          [optional]
        Writes info["emb"]     (B, T, D)
               info["act_emb"] (B, T, D)          [if action present]

        Mutates and returns the same dict.
        """

        pixels = info['pixels'].float()
        b = pixels.size(0)

        # The ViT sees images, not videos: fold time into the batch so every
        # frame is encoded independently.
        pixels = rearrange(pixels, "b t ... -> (b t) ...") # flatten for encoding

        # interpolate_pos_encoding lets the ViT accept an image size that
        # differs from the one its position embeddings were built for.
        output = self.encoder(pixels, interpolate_pos_encoding=True)

        # The CLS token is the ViT's summary of the whole image; patch tokens
        # are dropped. (B*T, D)
        pixels_emb = output.last_hidden_state[:, 0]  # cls token

        emb = self.projector(pixels_emb)
        info["emb"] = rearrange(emb, "(b t) d -> b t d", b=b)   # time back out

        if "action" in info:
            info["act_emb"] = self.action_encoder(info["action"])

        return info

    def predict(self, emb, act_emb):
        """Predict next state embedding
        emb: (B, T, D)
        act_emb: (B, T, A_emb)
        returns: (B, T, D) -- the predicted NEXT embedding for each timestep
        """
        preds = self.predictor(emb, act_emb)

        # pred_proj is an MLP with BatchNorm, which needs a flat batch axis,
        # so time is folded in and back out around it.
        preds = self.pred_proj(rearrange(preds, "b t d -> (b t) d"))
        preds = rearrange(preds, "(b t) d -> b t d", b=emb.size(0))
        return preds

    ####################
    ## Inference only ##
    ####################

    def rollout(self, info, action_sequence, history_size: int = 3):
        """Rollout the model given an initial info dict and action sequence.
        pixels: (B, S, T, C, H, W)
        action_sequence: (B, S, T, action_dim)
         - S is the number of action plan samples
         - T is the time horizon

        This is the model *imagining*. It encodes the real starting frames
        once, then repeatedly feeds its own predictions back in, never looking
        at a real image again. Writes info["predicted_emb"] (B, S, T', D).
        """

        assert "pixels" in info, "pixels not in info_dict"
        H = info["pixels"].size(2)
        B, S, T = action_sequence.shape[:3]

        # Split the plan: the first H actions accompany the real observed
        # frames, the rest are the future to imagine through.
        act_0, act_future = torch.split(action_sequence, [H, T - H], dim=2)
        info["action"] = act_0
        n_steps = T - H

        # Encode the real starting frames once. [:, 0] because every one of the
        # S candidate plans starts from the same observation.
        _init = {k: v[:, 0] for k, v in info.items() if torch.is_tensor(v)}
        _init = self.encode(_init)
        # expand (not repeat): a read-only broadcast view, no memory copied.
        emb = info["emb"] = _init["emb"].unsqueeze(1).expand(B, S, -1, -1)
        _init = {k: detach_clone(v) for k, v in _init.items()}

        # Treat the S plans as extra batch entries: one big parallel rollout.
        # .clone() because expand() gave a view and we are about to cat onto it.
        emb = rearrange(emb, "b s ... -> (b s) ...").clone()
        act = rearrange(act_0, "b s ... -> (b s) ...")
        act_future = rearrange(act_future, "b s ... -> (b s) ...")

        # rollout predictor autoregressively for n_steps
        HS = history_size
        for t in range(n_steps):
            act_emb = self.action_encoder(act)
            # Only the last HS steps are fed in: the predictor's position
            # embedding is sized for history_size, and it is Markovian enough.
            emb_trunc = emb[:, -HS:]  # (BS, HS, D)
            act_trunc = act_emb[:, -HS:]  # (BS, HS, A_emb)
            # [:, -1:] keeps only the newest prediction, as a length-1 slice.
            pred_emb = self.predict(emb_trunc, act_trunc)[:, -1:]  # (BS, 1, D)
            # The prediction becomes the next input: this is the imagination.
            emb = torch.cat([emb, pred_emb], dim=1)  # (BS, T+1, D)

            next_act = act_future[:, t : t + 1, :]  # (BS, 1, action_dim)
            act = torch.cat([act, next_act], dim=1)  # (BS, T+1, action_dim)

        # predict the last state
        act_emb = self.action_encoder(act)  # (BS, T, A_emb)
        emb_trunc = emb[:, -HS:]  # (BS, HS, D)
        act_trunc = act_emb[:, -HS:]  # (BS, HS, A_emb)
        pred_emb = self.predict(emb_trunc, act_trunc)[:, -1:]  # (BS, 1, D)
        emb = torch.cat([emb, pred_emb], dim=1)

        # unflatten batch and sample dimensions
        pred_rollout = rearrange(emb, "(b s) ... -> b s ...", b=B, s=S)
        info["predicted_emb"] = pred_rollout

        return info

    def criterion(self, info_dict: dict):
        """Compute the cost between predicted embeddings and goal embeddings.

        Only the FINAL step is scored: a plan is judged by where it ends up,
        not by the path it took. Returns (B, S) -- one cost per candidate plan.
        """
        pred_emb = info_dict["predicted_emb"]  # (B,S, T-1, dim)
        goal_emb = info_dict["goal_emb"]  # (B, S, T, dim)

        goal_emb = goal_emb[..., -1:, :].expand_as(pred_emb)

        # return last-step cost per action candidate
        cost = F.mse_loss(
            pred_emb[..., -1:, :],
            goal_emb[..., -1:, :].detach(),
            reduction="none",
        ).sum(dim=tuple(range(2, pred_emb.ndim)))  # (B, S)

        return cost

    def get_cost(self, info_dict: dict, action_candidates: torch.Tensor):
        """ Compute the cost of action candidates given an info dict with goal and initial state.

        This is the planning entry point. A planner (CEM, Adam, ...) proposes
        S candidate action sequences; this scores all of them in one batch, and
        the planner keeps the best. Returns (B, S).
        """

        assert "goal" in info_dict, "goal not in info_dict"

        device = next(self.parameters()).device
        for k in list(info_dict.keys()):
            if torch.is_tensor(info_dict[k]):
                info_dict[k] = info_dict[k].to(device)

        # Build an info dict for the goal image and encode it the same way as
        # an observation -- the goal is just another frame.
        goal = {k: v[:, 0] for k, v in info_dict.items() if torch.is_tensor(v)}
        goal["pixels"] = goal["goal"]

        # Strip the "goal_" prefix so encode() sees the keys it expects.
        for k in info_dict:
            if k.startswith("goal_"):
                goal[k[len("goal_") :]] = goal.pop(k)

        goal.pop("action")
        goal = self.encode(goal)

        info_dict["goal_emb"] = goal["emb"]
        info_dict = self.rollout(info_dict, action_candidates)

        cost = self.criterion(info_dict)

        return cost
