"""The small neural-network parts LeWM is assembled from. This notebook is the **source** for `lewm/module.py` — edit here, then run `uv run nbdev-export`."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_module.ipynb.

# %% auto #0
__all__ = ['modulate', 'SIGReg', 'FeedForward', 'Attention', 'ConditionalBlock', 'Block', 'Transformer', 'Embedder', 'MLP',
           'ARPredictor']

# %% ../nbs/00_module.ipynb #a31972c5
import torch
from torch import nn
import torch.nn.functional as F
from einops import rearrange

# %% ../nbs/00_module.ipynb #2bea1c2f
def modulate(x, shift, scale):
    """AdaLN-zero modulation

    x, shift, scale: all broadcastable, typically (B, T, D).
    Returns the same shape as x.

    With shift=scale=0 this returns x unchanged, so a freshly initialised
    block is the identity and conditioning is learned from zero.
    """
    return x * (1 + scale) + shift

# %% ../nbs/00_module.ipynb #f6b39b2b
class SIGReg(torch.nn.Module):
    """Sketch Isotropic Gaussian Regularizer (single-GPU!)

    Penalises embeddings for not looking like an isotropic Gaussian, which is
    what stops the encoder collapsing to a constant.

    Args:
        knots: quadrature points for the Epps-Pulley integral over t in [0, 3].
        num_proj: how many random 1-D directions to test per call. More
            projections means a lower-variance estimate at linear cost.
    """

    def __init__(self, knots=17, num_proj=1024):
        super().__init__()
        self.num_proj = num_proj

        # Quadrature grid over t in [0, 3]: where we sample the characteristic
        # function. Beyond t=3 the Gaussian window below is ~1e-5, so the
        # integrand is negligible and the range can stop there.
        t = torch.linspace(0, 3, knots, dtype=torch.float32)   # (knots,)
        dt = 3 / (knots - 1)

        # Trapezoid rule: interior points get full weight 2*dt, the two
        # endpoints get half that.
        weights = torch.full((knots,), 2 * dt, dtype=torch.float32)
        weights[[0, -1]] = dt

        # phi(t) = exp(-t^2/2): the characteristic function of a standard
        # Gaussian, and simultaneously the weighting window w(t).
        window = torch.exp(-t.square() / 2.0)                  # (knots,)

        # Buffers, not parameters: fixed constants that must follow the module
        # across .to(device) but are never trained.
        self.register_buffer("t", t)
        self.register_buffer("phi", window)
        self.register_buffer("weights", weights * window)

    def forward(self, proj):
        """
        proj: (T, B, D)  -- note time first; train.py passes emb.transpose(0, 1)
        returns: scalar
        """
        # 1. Random unit directions: (D, num_proj)
        A = torch.randn(proj.size(-1), self.num_proj, device=proj.device)
        A = A.div_(A.norm(p=2, dim=0))          # normalise each column to length 1

        # 2. Project onto every direction, then evaluate at every knot t.
        #    proj @ A          -> (T, B, num_proj)
        #    .unsqueeze(-1)*t  -> (T, B, num_proj, knots)
        x_t = (proj @ A).unsqueeze(-1) * self.t

        # 3. Empirical characteristic function, averaged over the batch (dim -3):
        #       real part  E[cos(tx)]  should equal phi(t)
        #       imag part  E[sin(tx)]  should equal 0
        #    err is the squared distance between the two, per (T, num_proj, knots).
        err = (x_t.cos().mean(-3) - self.phi).square() + x_t.sin().mean(-3).square()

        # 4. Integrate over t with the trapezoid weights, scale by batch size
        #    (the Epps-Pulley statistic is defined with an n factor).
        statistic = (err @ self.weights) * proj.size(-2)   # (T, num_proj)

        return statistic.mean() # average over projections and time

# %% ../nbs/00_module.ipynb #fc6a4ae4
class FeedForward(nn.Module):
    """FeedForward network used in Transformers

    (B, T, dim) -> (B, T, dim), widening to hidden_dim in the middle.
    """

    def __init__(self, dim, hidden_dim, dropout=0.0):
        super().__init__()
        self.net = nn.Sequential(
            nn.LayerNorm(dim),
            nn.Linear(dim, hidden_dim),   # widen
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, dim),   # back to dim
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

# %% ../nbs/00_module.ipynb #5121b995
class Attention(nn.Module):
    """Scaled dot-product attention with causal masking"""

    def __init__(self, dim, heads=8, dim_head=64, dropout=0.0):
        super().__init__()
        inner_dim = dim_head * heads

        # With a single head of exactly dim width, the output projection would
        # be a redundant square matmul, so it is skipped.
        project_out = not (heads == 1 and dim_head == dim)

        self.heads = heads
        self.scale = dim_head**-0.5
        self.dropout = dropout
        self.norm = nn.LayerNorm(dim)
        self.attend = nn.Softmax(dim=-1)

        # One fused projection producing q, k and v together, split below.
        self.to_qkv = nn.Linear(dim, inner_dim * 3, bias=False)

        self.to_out = (
            nn.Sequential(nn.Linear(inner_dim, dim), nn.Dropout(dropout))
            if project_out
            else nn.Identity()
        )

    def forward(self, x, causal=True):
        """
        x : (B, T, D)  ->  (B, T, D)

        causal=True masks the future: step t sees only steps <= t. This is what
        keeps the predictor honest -- without it, it could read the answer.
        """
        x = self.norm(x)
        drop = self.dropout if self.training else 0.0

        qkv = self.to_qkv(x).chunk(3, dim=-1)  # q, k, v: (B, heads, T, dim_head)
        q, k, v = (rearrange(t, "b t (h d) -> b h t d", h=self.heads) for t in qkv)

        # Fused kernel: handles the scale, the causal mask and the softmax.
        out = F.scaled_dot_product_attention(q, k, v, dropout_p=drop, is_causal=causal)

        out = rearrange(out, "b h t d -> b t (h d)")
        return self.to_out(out)

# %% ../nbs/00_module.ipynb #e844e6a3
class ConditionalBlock(nn.Module):
    """Transformer block with AdaLN-zero conditioning

    forward(x, c): x is the sequence (B, T, D), c is the conditioning signal
    (B, T, D) -- here, the encoded action.
    """

    def __init__(self, dim, heads, dim_head, mlp_dim, dropout=0.0):
        super().__init__()

        self.attn = Attention(dim, heads=heads, dim_head=dim_head, dropout=dropout)
        self.mlp = FeedForward(dim, mlp_dim, dropout=dropout)

        # elementwise_affine=False: these norms have no learnable scale/bias of
        # their own, because the modulation below supplies exactly that, per
        # example and per timestep.
        self.norm1 = nn.LayerNorm(dim, elementwise_affine=False, eps=1e-6)
        self.norm2 = nn.LayerNorm(dim, elementwise_affine=False, eps=1e-6)

        # c -> 6 * dim, later chunked into the six modulation vectors.
        self.adaLN_modulation = nn.Sequential(
            nn.SiLU(), nn.Linear(dim, 6 * dim, bias=True)
        )

        # The "zero" of AdaLN-zero: start as the identity, learn to condition.
        nn.init.constant_(self.adaLN_modulation[-1].weight, 0)
        nn.init.constant_(self.adaLN_modulation[-1].bias, 0)

    def forward(self, x, c):
        # Six (B, T, D) vectors from one (B, T, 6D) projection.
        shift_msa, scale_msa, gate_msa, shift_mlp, scale_mlp, gate_mlp = (
            self.adaLN_modulation(c).chunk(6, dim=-1)
        )
        # gate_* starts at 0, so both residual updates start at zero.
        x = x + gate_msa * self.attn(modulate(self.norm1(x), shift_msa, scale_msa))
        x = x + gate_mlp * self.mlp(modulate(self.norm2(x), shift_mlp, scale_mlp))
        return x

# %% ../nbs/00_module.ipynb #0c9cbcca
class Block(nn.Module):
    """Standard Transformer block

    (B, T, D) -> (B, T, D). No conditioning: forward takes x only.
    """

    def __init__(self, dim, heads, dim_head, mlp_dim, dropout=0.0):
        super().__init__()

        self.attn = Attention(dim, heads=heads, dim_head=dim_head, dropout=dropout)
        self.mlp = FeedForward(dim, mlp_dim, dropout=dropout)
        self.norm1 = nn.LayerNorm(dim, elementwise_affine=False, eps=1e-6)
        self.norm2 = nn.LayerNorm(dim, elementwise_affine=False, eps=1e-6)

    def forward(self, x):
        x = x + self.attn(self.norm1(x))
        x = x + self.mlp(self.norm2(x))
        return x

# %% ../nbs/00_module.ipynb #69b377ae
class Transformer(nn.Module):
    """Standard Transformer with support for AdaLN-zero blocks

    (B, T, input_dim) -> (B, T, output_dim)
    """

    def __init__(
        self,
        input_dim,
        hidden_dim,
        output_dim,
        depth,
        heads,
        dim_head,
        mlp_dim,
        dropout=0.0,
        block_class=Block,
    ):
        super().__init__()
        self.norm = nn.LayerNorm(hidden_dim)
        self.layers = nn.ModuleList([])

        # Identity when the widths already agree -- no wasted matmul.
        self.input_proj = (
            nn.Linear(input_dim, hidden_dim)
            if input_dim != hidden_dim
            else nn.Identity()
        )

        self.cond_proj = (
            nn.Linear(input_dim, hidden_dim)
            if input_dim != hidden_dim
            else nn.Identity()
        )

        self.output_proj = (
            nn.Linear(hidden_dim, output_dim)
            if hidden_dim != output_dim
            else nn.Identity()
        )

        for _ in range(depth):
            self.layers.append(
                block_class(hidden_dim, heads, dim_head, mlp_dim, dropout)
            )

    def forward(self, x, c=None):

        if hasattr(self, "input_proj"):
            x = self.input_proj(x)

        if c is not None and hasattr(self, "cond_proj"):
            c = self.cond_proj(c)

        # Plain Blocks take x only; ConditionalBlocks also take c.
        for block in self.layers:
            x = block(x) if isinstance(block, Block) else block(x, c)
        x = self.norm(x)

        if hasattr(self, "output_proj"):
            x = self.output_proj(x)
        return x

# %% ../nbs/00_module.ipynb #0ab51335
class Embedder(nn.Module):
    """Lift raw actions (B, T, A) into embeddings (B, T, emb_dim).

    Args:
        input_dim: raw action width A. In this repo it is
            frameskip * action_dim (5 * 2 = 10 for PushT), because each step
            of the dataset stacks the actions of 5 simulator frames.
        smoothed_dim: width after the 1x1 conv.
        emb_dim: final embedding width, matched to the predictor (192).
        mlp_scale: hidden-width multiplier inside the MLP.
    """

    def __init__(
        self,
        input_dim=10,
        smoothed_dim=10,
        emb_dim=10,
        mlp_scale=4,
    ):
        super().__init__()
        # kernel_size=1 over time == a per-timestep linear map. No mixing
        # across timesteps happens here.
        self.patch_embed = nn.Conv1d(input_dim, smoothed_dim, kernel_size=1, stride=1)
        self.embed = nn.Sequential(
            nn.Linear(smoothed_dim, mlp_scale * emb_dim),
            nn.SiLU(),
            nn.Linear(mlp_scale * emb_dim, emb_dim),
        )

    def forward(self, x):
        """
        x: (B, T, D)
        """
        x = x.float()
        x = x.permute(0, 2, 1)     # (B, T, A) -> (B, A, T) for Conv1d
        x = self.patch_embed(x)    # (B, smoothed_dim, T)
        x = x.permute(0, 2, 1)     # back to (B, T, smoothed_dim)
        x = self.embed(x)          # (B, T, emb_dim)
        return x

# %% ../nbs/00_module.ipynb #59f3884c
class MLP(nn.Module):
    """Simple MLP with optional normalization and activation

    (N, input_dim) -> (N, output_dim), where N is typically B*T.
    """

    def __init__(
        self,
        input_dim,
        hidden_dim,
        output_dim=None,
        norm_fn=nn.LayerNorm,
        act_fn=nn.GELU,
    ):
        super().__init__()
        # The config passes BatchNorm1d here, which needs a flat batch axis --
        # hence the (B*T, D) input convention.
        norm_fn = norm_fn(hidden_dim) if norm_fn is not None else nn.Identity()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            norm_fn,
            act_fn(),
            nn.Linear(hidden_dim, output_dim or input_dim),
        )

    def forward(self, x):
        """
        x: (B*T, D)
        """
        return self.net(x)

# %% ../nbs/00_module.ipynb #a598833c
class ARPredictor(nn.Module):
    """Autoregressive predictor for next-step embedding prediction.

    forward(x, c): x is (B, T, input_dim) embeddings, c is (B, T, input_dim)
    action embeddings. Returns (B, T, output_dim): the predicted *next*
    embedding for each timestep.

    Args:
        num_frames: longest sequence the position embedding supports. Equals
            history_size (3) in this repo.
    """

    def __init__(
        self,
        *,
        num_frames,
        depth,
        heads,
        mlp_dim,
        input_dim,
        hidden_dim,
        output_dim=None,
        dim_head=64,
        dropout=0.0,
        emb_dropout=0.0,
    ):
        super().__init__()
        # Learned position codes: attention is permutation-invariant without them.
        self.pos_embedding = nn.Parameter(torch.randn(1, num_frames, input_dim))
        self.dropout = nn.Dropout(emb_dropout)
        self.transformer = Transformer(
            input_dim,
            hidden_dim,
            output_dim or input_dim,
            depth,
            heads,
            dim_head,
            mlp_dim,
            dropout,
            block_class=ConditionalBlock,   # conditioned on the action
        )

    def forward(self, x, c):
        """
        x: (B, T, d)
        c: (B, T, act_dim)
        """
        T = x.size(1)
        x = x + self.pos_embedding[:, :T]   # slice: sequences may be shorter
        x = self.dropout(x)
        x = self.transformer(x, c)
        return x
