"""Image preprocessing, column normalisation, and saving checkpoints. Exports to `lewm/utils.py`."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_utils.ipynb.

# %% auto #0
__all__ = ['get_img_preprocessor', 'ZScoreNormalizer', 'get_column_normalizer', 'SaveCkptCallback']

# %% ../nbs/02_utils.ipynb #a21ac7ad
from collections.abc import Callable
from typing import Any

import numpy as np
import torch
from lightning.pytorch import LightningModule, Trainer
from lightning.pytorch.callbacks import Callback
from omegaconf import DictConfig
from stable_pretraining import data as dt

# %% ../nbs/02_utils.ipynb #6872de8a
def get_img_preprocessor(
    source: str, target: str, img_size: int = 224
) -> Callable[[dict[str, Any]], dict[str, Any]]:
    """Build the pixel transform: uint8 image -> normalised, resized float tensor.

    source / target: the dict keys to read from and write to, e.g. "pixels".
    """
    imagenet_stats = dt.dataset_stats.ImageNet
    to_image = dt.transforms.ToImage(**imagenet_stats, source=source, target=target)
    resize = dt.transforms.Resize(img_size, source=source, target=target)
    return dt.transforms.Compose(to_image, resize)

# %% ../nbs/02_utils.ipynb #4467ec73
class ZScoreNormalizer:
    """Picklable z-score normalizer — uses a class instead of a closure so it
    survives pickle when DataLoader workers are spawned (required by LanceDataset).

    A lambda or nested function would raise PicklingError when the DataLoader
    tries to send it to a worker process.
    """

    def __init__(self, mean: torch.Tensor, std: torch.Tensor) -> None:
        self.mean = mean
        self.std = std

    def __call__(self, x: torch.Tensor) -> torch.Tensor:
        return ((x - self.mean) / self.std).float()

# %% ../nbs/02_utils.ipynb #76c37f94
def get_column_normalizer(
    dataset: Any, source: str, target: str
) -> Callable[[dict[str, Any]], dict[str, Any]]:
    """Get normalizer for a specific column in the dataset.

    Computes mean and std over the entire column once, ignoring NaN rows,
    and returns a picklable transform that applies them.
    """
    col_data = dataset.get_col_data(source)
    data = torch.from_numpy(np.array(col_data))

    # Drop NaN rows (episode boundaries) -- one NaN would make mean/std NaN.
    data = data[~torch.isnan(data).any(dim=1)]

    # .clone() so the stats don't keep the whole column tensor alive.
    mean = data.mean(0, keepdim=True).clone()
    std = data.std(0, keepdim=True).clone()
    return dt.transforms.WrapTorchTransform(ZScoreNormalizer(mean, std), source=source, target=target)

# %% ../nbs/02_utils.ipynb #505442cb
class SaveCkptCallback(Callback):
    """Callback to save model checkpoint after each epoch using save_pretrained.

    Args:
        run_name: checkpoint name, relative to $STABLEWM_HOME.
        cfg: the model config, stored alongside the weights so the checkpoint
            can be rebuilt without the original Hydra run.
        epoch_interval: save every N epochs.
    """

    def __init__(
        self, run_name: str, cfg: DictConfig, epoch_interval: int = 1
    ) -> None:
        super().__init__()
        self.run_name = run_name
        self.cfg = cfg
        self.epoch_interval = epoch_interval

    def on_train_epoch_end(
        self, trainer: Trainer, pl_module: LightningModule
    ) -> None:
        super().on_train_epoch_end(trainer, pl_module)

        # Multi-GPU: every rank runs this callback, but only rank 0 writes.
        if trainer.is_global_zero:
            if (trainer.current_epoch + 1) % self.epoch_interval == 0:
                self._save(pl_module.model, trainer.current_epoch + 1)

            # Always save the final epoch, even if it isn't on the interval.
            if (trainer.current_epoch + 1) == trainer.max_epochs:
                self._save(pl_module.model, trainer.current_epoch + 1)

    def _save(self, model: torch.nn.Module, epoch: int) -> None:
        # Imported here rather than at module level: defers the cost and
        # avoids a circular import.
        from stable_worldmodel.wm.utils import save_pretrained
        save_pretrained(
            model,
            run_name=self.run_name,
            config=self.cfg,
            filename=f'weights_epoch_{epoch}.pt',
        )
